### PR TITLE
Fix Guild::member_named V0.5.0

### PR DESCRIPTION
**Pull request by tahahawa**
Made changes as requested, tests might be a bit jank, but they seem to work. Targeting the 5.0 branch

### CODE REVIEW

**Comment by tahahawa** [comment]
Looking at this comment is how I designed the tests:
```
The following are valid types of searches:
**username**: "zey"
**username and discriminator**: "zey#5479"
**nickname**: "zeyla" or "zeylas#nick"
```
It seems the last case (nickname explicit search) wasn't implemented. That's what's causing the test fail. Should we remove that from the docs/comment, and remove the test? Or, implement it?

**Comment by zeyla** [comment]
Let's remove the mention in the documentation and tests and leave the implementation for a different commit.

**Comment by tahahawa** [comment]
Looks like the tests passed! 🙌

**Comment by zeyla** [comment]
There seems to be a lot of random code style changes here, can we cut those out?

**Comment by tahahawa** [comment]
Done

**Comment by tahahawa** [comment]
Oops, forgot to fix the new testing stuff

**Comment by tahahawa** [comment]
I think this is ready to merge, unless there's anything else to do

**Comment by zeyla** [comment]
Thanks

**Pull request merged**
