### PR TITLE
Added package.metadata.docs.rs at Cargo.toml to enable voice feature docs generation

### PR DESCRIPTION
**Pull request by MOZGIII**
According to this code it should work: https://github.com/onur/docs.rs/blob/13da7b2cd11fd6ea954c1d0145490586411700a4/src/docbuilder/metadata.rs#L19

### CODE REVIEW

**Comment by acdenisSK** [comment]
This is already done in [v0.5.0](https://github.com/zeyla/serenity/blob/v0.5.0/Cargo.toml#L116-L117).

**Comment by MOZGIII** [comment]
I see. Why it's not in master?

**Comment by acdenisSK** [comment]
Because it's pointless, since docs.rs does not generate docs for unreleased code (not on crates.io).
Plus, master isn't the right branch for pr'ing stuff like this; nor are we using it as a dev branch.

**Comment by MOZGIII** [comment]
Well, that's sad; there's no indication that master is not the dev branch.
I noticed you also seem to have release branches - what's the point of having a master branch?
Where can I learn more about the conventions this project is using?

**Comment by acdenisSK** [comment]
`what's the point of having a master branch?`
The point is for linking to serenity's examples correctly and such; or for a more appropriate explanation: https://github.com/zeyla/serenity/issues/230#issuecomment-350499993

`Where can I learn more about the conventions this project is using?`
We don't a list for that yet, but is soon to arrive after v0.5.0 is released.

**Pull request closed without merging**
